name: ViperMultiModule

options:
  bundleIdPrefix: com.hicka04.viper_multi_module
  deploymentTarget:
    iOS: 13.0

targets:
  App:
    type: application
    platform: iOS
    sources:
     - App
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
    dependencies:
      - package: Feature
      - package: Logic
    scheme:
      testTargets:
        - name: AppTests
          parallelizable: true
          randomExecutionOrder: true
      gatherCoverageData: true

  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
     - AppTests
    settings:
      base:
        INFOPLIST_FILE: AppTests/Info.plist
    dependencies:
      - target: App

packages:
  Feature:
    path: ./Feature
  Logic:
    path: ./Logic