name: ViperMultiModule

options:
  bundleIdPrefix: com.hicka04.viper_multi_module
  deploymentTarget:
    iOS: 13.0

targets:
  ViperMultiModule:
    type: application
    platform: iOS
    sources:
     - ViperMultiModule
    settings:
      base:
        INFOPLIST_FILE: ViperMultiModule/Info.plist
    dependencies:
      - package: Feature
      - package: Logic
    scheme:
      testTargets:
        - name: ViperMultiModuleTests
          parallelizable: true
          randomExecutionOrder: true
      gatherCoverageData: true

  ViperMultiModuleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
     - ViperMultiModuleTests
    settings:
      base:
        INFOPLIST_FILE: ViperMultiModuleTests/Info.plist
    dependencies:
      - target: ViperMultiModule

packages:
  Feature:
    path: ./Feature
  Logic:
    path: ./Logic